# Generated by Django 5.2.5 on 2025-08-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='overpaid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
