# Generated by Django 5.2.5 on 2025-08-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_employee_count',
            field=models.IntegerField(default=10),
        ),
    ]
