from .create import DeparmentCreateAPIView
from .detail import DepartmentRetrieveAPIView, DeparmentDeleteAPIView, DepartmentUpdateAPIView
from .list import DepartmentOrganizationListAPIView, DepartmentEmployeesAPIView
