# Generated by Django 5.2.5 on 2025-08-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='position',
            table='position',
        ),
    ]
