# Generated by Django 5.2.5 on 2025-09-01 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='descreption',
            new_name='description',
        ),
    ]
