# Generated by Django 5.2.5 on 2025-08-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('descreption', models.CharField(blank=True, max_length=600, null=True)),
            ],
            options={
                'db_table': 'department',
            },
        ),
    ]
