# Generated by Django 5.2.5 on 2025-08-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='department',
            name='max_employee',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
