# Generated by Django 5.2.5 on 2025-08-23 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_department_is_active_department_max_employee'),
        ('employee', '0002_alter_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='employee.employee'),
        ),
    ]
