# Generated by Django 5.2.5 on 2025-08-24 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_department_leader'),
        ('employee', '0002_alter_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='leader',
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='employee.employee'),
        ),
    ]
