# Generated by Django 5.2.5 on 2025-09-01 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_remove_department_leader_department_head'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='descreption',
            new_name='description',
        ),
    ]
