# Generated by Django 5.2.5 on 2025-08-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_organization_one_id_organization_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
