# Generated by Django 5.2.5 on 2025-08-23 16:33

import apps.employee.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('position', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('passport_number', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Passport number must be in format: 2 uppercase letters + 7 digits (e.g. AB1234567).', regex='^[A-Z]{2}\\d{7}$')])),
                ('jshshir', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='JShShIR must be exactly 14 digits.', regex='^\\d{14}$')])),
                ('birth_date', models.DateField(blank=True, null=True, validators=[apps.employee.validators.validate_birth_date])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('vacation', 'Vacation'), ('fired', 'Fired')], default='active', max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='department.department')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='position.position')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
