# Generated by Django 5.2.5 on 2025-09-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_head',
            field=models.BooleanField(default=False),
        ),
    ]
